# Generated by Django 3.0.7 on 2021-03-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_access_daily_attend_report', 'Can accces Daily Attend report'), ('can_access_gpm403_daily_guard_performance_by_contract_report', 'Can accces GPM403 Daily Guard Performance by Contract eport')),
            },
        ),
    ]
