# Generated by Django 3.0.7 on 2021-03-17 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyattendreport', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerReport',
            new_name='DailyAttendReport',
        ),
    ]
