# Generated by Django 3.0.7 on 2021-03-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dailyattendreport', '0002_auto_20210317_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyattendreport',
            options={'permissions': (('can_access_daily_attend_report', 'Can accces Daily Attend report'), ('can_access_gpm403_daily_guard_performance_by_contract_report', 'Can accces GPM403 Daily Guard Performance by Contract report'), ('can_access_gpm_work_on_day_off_report', 'Can accces GPM Work on Day Off report'))},
        ),
    ]
