# Generated by Django 3.0.7 on 2021-03-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractreport', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EleaveReports',
            new_name='ContractReport',
        ),
    ]
