# Generated by Django 3.0.7 on 2021-05-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractreport', '0002_auto_20210308_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractreport',
            options={'permissions': (('can_access_contract_menu_report', 'Can accces Contract Menu report'), ('can_access_contract_list_report', 'Can accces Contract List report'))},
        ),
    ]
