# Generated by Django 3.0.7 on 2021-05-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractreport', '0003_auto_20210520_1637'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractreport',
            options={'permissions': (('can_access_contract_menu_report', 'Can accces Contract Menu report'), ('can_access_contract_list_report', 'Can accces Contract List report'), ('can_access_post_manpower_report', 'Can accces Post Manpower report'))},
        ),
    ]
