# Generated by Django 3.0.7 on 2021-05-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractreport', '0004_auto_20210522_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractreport',
            options={'permissions': (('can_access_contract_menu_report', 'Can accces Contract Menu report'), ('can_access_contract_list_report', 'Can accces Contract List report'))},
        ),
    ]
