# Generated by Django 3.0.7 on 2020-09-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuscontract',
            options={'managed': True},
        ),
    ]
