# Generated by Django 3.0.7 on 2020-08-03 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_twagezone'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuscontract',
            name='cnt_wage_id',
            field=models.ForeignKey(db_column='cnt_wage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.TWagezone'),
        ),
    ]
