# Generated by Django 3.0.7 on 2020-09-24 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_hrmsnewlog'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuscontract',
            name='cnt_wage_id',
            field=models.ForeignKey(db_column='cnt_wage_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cus_contract_t_wagezone_fk', to='system.TWagezone'),
        ),
    ]
