# Generated by Django 3.0.7 on 2020-07-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_cusservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusservice',
            name='cnt_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True),
        ),
    ]
