# Generated by Django 3.0.7 on 2020-09-28 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20200925_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuscontract',
            options={'managed': False},
        ),
    ]
