# Generated by Django 3.0.7 on 2020-08-03 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_groupbill'),
        ('contract', '0003_auto_20200803_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuscontract',
            name='cnt_apr_by',
            field=models.ForeignKey(db_column='cnt_apr_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.TAprove'),
        ),
    ]
