# Generated by Django 3.0.7 on 2020-07-31 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20200731_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusservice',
            name='cnt_id',
            field=models.ForeignKey(db_column='cnt_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.CusContract'),
        ),
    ]
