# Generated by Django 3.0.7 on 2020-07-31 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_auto_20200731_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cusservice',
            name='op1',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='op2',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='op3',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_active',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_cost',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_cost_change',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_cost_rate',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_eff_frm',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_eff_to',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_fri',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_mon',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_pub',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_qty',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_rate',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_rem',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_sat',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_shif_id',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_sun',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_thu',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_tue',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='srv_wed',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='upd_by',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='upd_date',
        ),
        migrations.RemoveField(
            model_name='cusservice',
            name='upd_flag',
        ),
    ]
