# Generated by Django 3.0.7 on 2020-07-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_auto_20200731_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('srv_id', models.DecimalField(decimal_places=0, max_digits=16, primary_key=True, serialize=False)),
                ('cnt_id', models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True)),
                ('srv_rank', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'test',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='CusService',
        ),
    ]
