# Generated by Django 3.0.7 on 2020-07-31 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_auto_20200731_1433'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='Test',
        ),
    ]
