# Generated by Django 2.2.10 on 2020-02-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('com_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('com_sht_th', models.CharField(blank=True, max_length=10, null=True)),
                ('com_name_th', models.CharField(blank=True, max_length=80, null=True)),
                ('com_add1_th', models.CharField(blank=True, max_length=50, null=True)),
                ('com_add2_th', models.CharField(blank=True, max_length=50, null=True)),
                ('com_subdist_th', models.CharField(blank=True, max_length=20, null=True)),
                ('com_sht_en', models.CharField(blank=True, max_length=10, null=True)),
                ('com_name_en', models.CharField(blank=True, max_length=80, null=True)),
                ('com_add1_en', models.CharField(blank=True, max_length=50, null=True)),
                ('com_add2_en', models.CharField(blank=True, max_length=50, null=True)),
                ('com_subdist_en', models.CharField(blank=True, max_length=20, null=True)),
                ('com_district', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('com_city', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('com_country', models.SmallIntegerField(blank=True, null=True)),
                ('com_zip', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('com_tel1', models.CharField(blank=True, max_length=15, null=True)),
                ('com_tel2', models.CharField(blank=True, max_length=15, null=True)),
                ('com_fax1', models.CharField(blank=True, max_length=15, null=True)),
                ('com_fax2', models.CharField(blank=True, max_length=15, null=True)),
                ('com_email', models.CharField(blank=True, max_length=20, null=True)),
                ('com_taxid', models.CharField(blank=True, max_length=13, null=True)),
                ('com_socid', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('com_brnid', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('com_soc_no', models.CharField(blank=True, max_length=2, null=True)),
                ('com_soc_brn', models.CharField(blank=True, max_length=6, null=True)),
                ('com_active', models.BooleanField(blank=True, null=True)),
                ('com_main', models.BooleanField(blank=True, null=True)),
                ('com_parent', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('com_hr_month', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('com_hr_day', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('com_md', models.DecimalField(blank=True, db_column='com_MD', decimal_places=0, max_digits=7, null=True)),
                ('com_admin', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('com_hr', models.DecimalField(blank=True, db_column='com_HR', decimal_places=0, max_digits=7, null=True)),
                ('com_acno', models.CharField(blank=True, max_length=12, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'COMPANY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TAprove',
            fields=[
                ('apr_id', models.DecimalField(decimal_places=0, max_digits=6, primary_key=True, serialize=False)),
                ('apr_title', models.SmallIntegerField(blank=True, null=True)),
                ('apr_name_th', models.CharField(blank=True, max_length=60, null=True)),
                ('apr_name_en', models.CharField(blank=True, max_length=60, null=True)),
                ('apr_pos_th', models.CharField(blank=True, max_length=50, null=True)),
                ('apr_pos_en', models.CharField(blank=True, max_length=50, null=True)),
                ('apr_piority', models.CharField(blank=True, max_length=3, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'T_APROVE',
                'managed': False,
            },
        ),
    ]
