# Generated by Django 2.2.10 on 2020-03-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taprove',
            name='apr_piority',
            field=models.CharField(choices=[('', 'เลือกรายการ'), ('ALL', 'ALL - Can approve all system'), ('PRM', 'PRM - Can approve customer performance system'), ('PSN', 'PSN - Can approve personel system')], default=None, max_length=3),
        ),
    ]
