# Generated by Django 3.0.7 on 2020-07-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cuscontact',
            index=models.Index(fields=['con_id'], name='CUS_CONTACT_con_id_70faec_idx'),
        ),
    ]
