# Generated by Django 2.2.10 on 2020-02-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTitle',
            fields=[
                ('title_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('title_th', models.CharField(blank=True, max_length=30, null=True)),
                ('title_en', models.CharField(blank=True, max_length=30, null=True)),
                ('title_sht_th', models.CharField(blank=True, max_length=10, null=True)),
                ('title_sht_en', models.CharField(blank=True, max_length=10, null=True)),
                ('title_sex', models.CharField(blank=True, max_length=1, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'T_TITLE',
                'managed': False,
            },
        ),
    ]
