# Generated by Django 3.0.7 on 2020-09-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comdepartment',
            options={'managed': False},
        ),
    ]
