# Generated by Django 2.2.10 on 2020-03-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200303_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taprove',
            name='apr_piority',
            field=models.CharField(choices=[('', '----------'), ('ALL', 'ALL - Can approve all system'), ('PRM', 'PRM - Can approve customer performance system'), ('PSN', 'PSN - Can approve personel system')], default=None, max_length=3),
        ),
        migrations.AlterField(
            model_name='taprove',
            name='upd_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
