# Generated by Django 2.2.10 on 2020-02-26 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_ttitle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taprove',
            options={},
        ),
    ]
