# Generated by Django 3.0.7 on 2020-09-18 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20200918_0841'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comdepartment',
            options={'managed': True},
        ),
    ]
