# Generated by Django 3.0.7 on 2020-09-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200918_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuscontact',
            name='cus_id',
            field=models.DecimalField(decimal_places=0, max_digits=7),
        ),
    ]
