# Generated by Django 2.2.10 on 2020-02-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200226_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taprove',
            options={'managed': False},
        ),
    ]
