# Generated by Django 3.0.7 on 2020-07-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_tcity_tcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupbill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.FloatField(blank=True, db_column='Post', null=True)),
                ('cnt_id', models.CharField(blank=True, db_column='Cnt_id', max_length=255, null=True)),
                ('groupcom', models.CharField(blank=True, db_column='GroupCom', max_length=255, null=True)),
            ],
            options={
                'db_table': 'groupbill',
                'managed': False,
            },
        ),
    ]
