# Generated by Django 3.0.7 on 2020-09-30 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_hrmsnewlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TShift',
            fields=[
                ('shf_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('shf_type', models.CharField(blank=True, max_length=1, null=True)),
                ('shf_desc', models.CharField(blank=True, max_length=30, null=True)),
                ('shf_time_frm', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('shf_time_to', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('shf_amt_hr', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shf_order', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'T_SHIFT',
                'managed': False,
            },
        ),
    ]
