# Generated by Django 3.0.7 on 2020-09-17 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200917_0811'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newhrmslog',
            table='new_hrms_log',
        ),
    ]
