# Generated by Django 2.2.10 on 2020-03-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20200304_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComZone',
            fields=[
                ('zone_id', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('zone_th', models.CharField(blank=True, max_length=30, null=True)),
                ('zone_en', models.CharField(blank=True, max_length=30, null=True)),
                ('zone_emp_id', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'COM_ZONE',
                'managed': False,
            },
        ),
    ]
