# Generated by Django 3.0.7 on 2020-09-17 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_hrmsnewlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HrmsNewLog',
        ),
    ]
