# Generated by Django 3.0.7 on 2020-08-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_groupbill'),
    ]

    operations = [
        migrations.CreateModel(
            name='TWagezone',
            fields=[
                ('wage_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('wage_th', models.CharField(blank=True, max_length=30, null=True)),
                ('wage_en', models.CharField(blank=True, max_length=30, null=True)),
                ('wage_city', models.SmallIntegerField(blank=True, null=True)),
                ('wage_8hr', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('owage_8hr', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('wage_en_tmp', models.CharField(blank=True, max_length=50, null=True)),
                ('w2010', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('w2009', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('w2008', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('w2007', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('w2006', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('w2005', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('w2004', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'T_WAGEZONE',
                'managed': False,
            },
        ),
    ]
