# Generated by Django 2.2.10 on 2020-03-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200226_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttitle',
            options={'managed': True},
        ),
    ]
