# Generated by Django 3.0.7 on 2020-09-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_tshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComRank',
            fields=[
                ('rank_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('rank_th', models.CharField(blank=True, max_length=30, null=True)),
                ('rank_en', models.CharField(blank=True, max_length=30, null=True)),
                ('rank_type', models.CharField(blank=True, max_length=3, null=True)),
                ('rank_start', models.DateTimeField(blank=True, null=True)),
                ('rank_grd', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('rank_promot', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'COM_RANK',
                'managed': False,
            },
        ),
    ]
