# Generated by Django 2.2.10 on 2020-03-05 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_comzone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comzone',
            options={'managed': True},
        ),
    ]
