# Generated by Django 3.0.7 on 2020-08-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_twagezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusGroup',
            fields=[
                ('gname', models.CharField(db_column='Gname', max_length=30, primary_key=True, serialize=False)),
                ('gcode', models.CharField(blank=True, db_column='Gcode', max_length=10, null=True)),
                ('upd', models.DateTimeField(blank=True, db_column='Upd', null=True)),
                ('upd_flag', models.CharField(blank=True, db_column='Upd_flag', max_length=1, null=True)),
                ('upd_by', models.CharField(blank=True, db_column='Upd_By', max_length=30, null=True)),
                ('op1', models.CharField(blank=True, max_length=10, null=True)),
                ('op2', models.CharField(blank=True, max_length=10, null=True)),
                ('op3', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'CUS_GROUP',
                'managed': False,
            },
        ),
    ]
