# Generated by Django 2.2.10 on 2020-03-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20200302_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taprove',
            options={'managed': True},
        ),
    ]
