# Generated by Django 3.1.2 on 2020-10-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_comrank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'managed': False},
        ),
    ]
