# Generated by Django 3.0.7 on 2020-09-17 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_delete_hrmsnewlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrmsNewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_table', models.CharField(blank=True, db_column='log_table', max_length=50, null=True)),
                ('log_field', models.CharField(blank=True, db_column='log_field', max_length=500, null=True)),
                ('log_old', models.CharField(blank=True, db_column='log_old', max_length=500, null=True)),
                ('log_new', models.CharField(blank=True, db_column='log_new', max_length=500, null=True)),
                ('log_type', models.CharField(blank=True, db_column='log_type', max_length=1, null=True)),
                ('log_by', models.CharField(blank=True, db_column='log_by', max_length=20, null=True)),
                ('log_date', models.DateTimeField(auto_now_add=True, db_column='log_date')),
            ],
            options={
                'db_table': 'hrms_new_log',
                'managed': True,
                'unique_together': {('id', 'log_date')},
            },
        ),
    ]
