# Generated by Django 2.2.10 on 2020-03-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_tdistrict'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TDistrict',
        ),
    ]
