# Generated by Django 3.0.7 on 2020-09-17 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_hrmsnewlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HrmsNewLog',
        ),
    ]
