# Generated by Django 3.0.7 on 2020-09-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20200921_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmsnewlog',
            name='log_table_name',
            field=models.CharField(blank=True, db_column='log_table_name', max_length=50, null=True),
        ),
    ]
