# Generated by Django 3.1.2 on 2020-10-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20201012_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='TNation',
            fields=[
                ('nation_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nation_th', models.CharField(blank=True, max_length=30, null=True)),
                ('nation_en', models.CharField(blank=True, max_length=30, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'T_NATION',
                'managed': False,
            },
        ),
    ]
