# Generated by Django 3.0.7 on 2020-09-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20200921_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrmsnewlog',
            name='log_table_name',
        ),
        migrations.AddField(
            model_name='hrmsnewlog',
            name='log_key',
            field=models.CharField(blank=True, db_column='log_key', max_length=50, null=True),
        ),
    ]
