# Generated by Django 3.1.2 on 2020-10-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20201015_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='TEmpsts',
            fields=[
                ('sts_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('sts_th', models.CharField(blank=True, max_length=50, null=True)),
                ('sts_en', models.CharField(blank=True, max_length=30, null=True)),
                ('sts_flag', models.BooleanField(blank=True, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'T_EMPSTS',
                'managed': False,
            },
        ),
    ]
