# Generated by Django 3.0.7 on 2020-09-21 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200921_0936'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HrmsNewLog',
        ),
    ]
