# Generated by Django 3.0.7 on 2020-09-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_delete_hrmsnewlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrmsNewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_table', models.CharField(blank=True, db_column='log_table', max_length=50, null=True)),
                ('log_key', models.CharField(blank=True, db_column='log_key', max_length=50, null=True)),
                ('log_field', models.CharField(blank=True, db_column='log_field', max_length=50, null=True)),
                ('old_value', models.CharField(blank=True, db_column='old_value', max_length=500, null=True)),
                ('new_value', models.CharField(blank=True, db_column='new_value', max_length=500, null=True)),
                ('log_type', models.CharField(blank=True, db_column='log_type', max_length=1, null=True)),
                ('log_by', models.CharField(blank=True, db_column='log_by', max_length=20, null=True)),
                ('log_date', models.DateTimeField(auto_now_add=True, db_column='log_date')),
                ('log_description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'hrms_new_log',
                'managed': True,
                'unique_together': {('id', 'log_date')},
            },
        ),
    ]
