# Generated by Django 3.1.2 on 2020-11-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_tempsts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TPeriod',
            fields=[
                ('prd_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('prd_year', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('prd_month', models.SmallIntegerField(blank=True, null=True)),
                ('period', models.SmallIntegerField(blank=True, null=True)),
                ('prd_order', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('prd_num', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('prd_date_frm', models.DateTimeField(blank=True, null=True)),
                ('prd_date_to', models.DateTimeField(blank=True, null=True)),
                ('prd_date_paid', models.DateTimeField(blank=True, null=True)),
                ('emp_type', models.CharField(blank=True, max_length=2, null=True)),
                ('com_id', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('prd_close', models.BooleanField(blank=True, null=True)),
                ('prd_process', models.BooleanField(blank=True, null=True)),
                ('prd_wrkday', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'T_PERIOD',
                'managed': False,
            },
        ),
    ]
