# Generated by Django 3.0.7 on 2020-07-21 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0003_tcity_tcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_no', models.DecimalField(decimal_places=0, max_digits=10, primary_key=True, serialize=False)),
                ('cus_id', models.DecimalField(decimal_places=0, max_digits=7)),
                ('cus_brn', models.DecimalField(decimal_places=0, max_digits=3)),
                ('cus_sht_th', models.CharField(blank=True, max_length=10, null=True)),
                ('cus_name_th', models.CharField(blank=True, max_length=120, null=True)),
                ('cus_add1_th', models.CharField(blank=True, max_length=150, null=True)),
                ('cus_add2_th', models.CharField(blank=True, max_length=70, null=True)),
                ('cus_subdist_th', models.CharField(blank=True, max_length=30, null=True)),
                ('cus_sht_en', models.CharField(blank=True, max_length=10, null=True)),
                ('cus_name_en', models.CharField(blank=True, max_length=120, null=True)),
                ('cus_add1_en', models.CharField(blank=True, max_length=150, null=True)),
                ('cus_add2_en', models.CharField(blank=True, max_length=70, null=True)),
                ('cus_subdist_en', models.CharField(blank=True, max_length=30, null=True)),
                ('cus_zip', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('cus_tel', models.CharField(blank=True, max_length=40, null=True)),
                ('cus_fax', models.CharField(blank=True, max_length=30, null=True)),
                ('cus_email', models.CharField(blank=True, max_length=60, null=True)),
                ('cus_taxid', models.CharField(blank=True, max_length=30, null=True)),
                ('cus_active', models.BooleanField(blank=True, null=True)),
                ('cus_bill', models.BooleanField(blank=True, null=True)),
                ('cus_main', models.BooleanField(blank=True, null=True)),
                ('cus_site', models.BooleanField(blank=True, null=True)),
                ('site_contact', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('last_contact', models.SmallIntegerField(blank=True, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('cus_city', models.ForeignKey(db_column='cus_city', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.TCity')),
                ('cus_contact', models.ForeignKey(db_column='cus_contact', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.CusContact')),
                ('cus_country', models.ForeignKey(db_column='cus_country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.TCountry')),
                ('cus_district', models.ForeignKey(db_column='cus_district', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.TDistrict')),
                ('cus_zone', models.ForeignKey(db_column='cus_zone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.ComZone')),
            ],
            options={
                'db_table': 'CUSTOMER',
                'ordering': ['cus_no'],
                'managed': True,
            },
        ),
    ]
