# Generated by Django 3.0.7 on 2020-08-10 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusbill',
            name='cus_city',
            field=models.ForeignKey(db_column='cus_city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bill_city', to='system.TCity'),
        ),
        migrations.AlterField(
            model_name='cusbill',
            name='cus_country',
            field=models.ForeignKey(db_column='cus_country', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bill_country', to='system.TCountry'),
        ),
        migrations.AlterField(
            model_name='cusbill',
            name='cus_district',
            field=models.ForeignKey(db_column='cus_district', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_bill_district', to='system.TDistrict'),
        ),
    ]
