# Generated by Django 2.2.10 on 2020-03-10 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_district',
            field=models.ForeignKey(db_column='cus_district', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.TDistrict'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_zone',
            field=models.ForeignKey(db_column='cus_zone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.ComZone'),
        ),
    ]
