# Generated by Django 3.0.7 on 2020-09-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20200918_1040'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusbill',
            name='cus_city',
            field=models.ForeignKey(db_column='cus_city', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cus_bill_t_city_fk', to='system.TCity'),
        ),
    ]
