# Generated by Django 3.0.7 on 2020-08-03 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_groupbill'),
        ('customer', '0002_auto_20200721_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_contact',
            field=models.ForeignKey(db_column='cus_contact', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.CusContact'),
        ),
    ]
