# Generated by Django 2.2.10 on 2020-03-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200304_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True},
        ),
    ]
