# Generated by Django 3.0.7 on 2020-08-26 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        ('customer', '0002_auto_20200824_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusbill',
            name='cus_contact',
            field=models.ForeignKey(db_column='cus_contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cus_bill_main_contact', to='system.CusContact'),
        ),
        migrations.AlterField(
            model_name='cusbill',
            name='cus_zone',
            field=models.ForeignKey(db_column='cus_zone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cus_bill_main_zone', to='system.ComZone'),
        ),
        migrations.AlterField(
            model_name='cusbill',
            name='site_contact',
            field=models.ForeignKey(db_column='site_contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cus_bill_main_site_contact', to='system.CusContact'),
        ),
    ]
