# Generated by Django 2.2.10 on 2020-03-05 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200304_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_zone',
            field=models.ForeignKey(db_column='cus_zone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.ComZone'),
        ),
    ]
