# Generated by Django 3.0.7 on 2020-07-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200720_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='TCity',
            fields=[
                ('city_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('country_id', models.SmallIntegerField(blank=True, null=True)),
                ('city_th', models.CharField(blank=True, max_length=30, null=True)),
                ('city_en', models.CharField(blank=True, max_length=30, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'T_CITY',
                'managed': False,
            },
        ),
    ]
