# Generated by Django 3.0.7 on 2020-08-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_cusmain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cusmain',
            options={'managed': True},
        ),
    ]
