# Generated by Django 3.0.7 on 2020-08-07 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_cusgroup'),
        ('customer', '0006_auto_20200807_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cusmain',
            name='cus_district',
            field=models.ForeignKey(db_column='cus_district', null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.TDistrict'),
        ),
    ]
