# Generated by Django 3.0.7 on 2020-08-07 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200807_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_main',
            field=models.ForeignKey(db_column='cus_main', null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.CusMain'),
        ),
    ]
