# Generated by Django 3.0.7 on 2020-08-10 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.DecimalField(decimal_places=0, max_digits=7, primary_key=True, serialize=False)),
                ('emp_title', models.SmallIntegerField()),
                ('emp_fname_en', models.CharField(blank=True, max_length=30, null=True)),
                ('emp_lname_en', models.CharField(blank=True, max_length=40, null=True)),
                ('emp_fname_th', models.CharField(blank=True, max_length=30, null=True)),
                ('emp_lname_th', models.CharField(blank=True, max_length=40, null=True)),
                ('emp_birth', models.DateTimeField(blank=True, null=True)),
                ('emp_age', models.SmallIntegerField(blank=True, null=True)),
                ('emp_sex', models.CharField(blank=True, max_length=1, null=True)),
                ('emp_scar_th', models.CharField(blank=True, max_length=30, null=True)),
                ('emp_scar_en', models.CharField(blank=True, max_length=30, null=True)),
                ('emp_race', models.SmallIntegerField(blank=True, null=True)),
                ('emp_nation', models.SmallIntegerField(blank=True, null=True)),
                ('emp_religion', models.SmallIntegerField(blank=True, null=True)),
                ('emp_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emp_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emp_military', models.CharField(blank=True, max_length=1, null=True)),
                ('emp_citizen_type', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_citizen_id', models.CharField(blank=True, max_length=13, null=True)),
                ('emp_issue_date', models.DateTimeField(blank=True, null=True)),
                ('emp_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('emp_issue_place', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('emp_issue_city', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('emp_issue_country', models.SmallIntegerField(blank=True, null=True)),
                ('emp_type', models.CharField(blank=True, max_length=2, null=True)),
                ('emp_com', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('emp_brn', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('emp_div', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('emp_dept', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('emp_sect', models.SmallIntegerField(blank=True, null=True)),
                ('emp_position', models.SmallIntegerField(blank=True, null=True)),
                ('emp_rank', models.CharField(blank=True, max_length=3, null=True)),
                ('emp_grade', models.SmallIntegerField(blank=True, null=True)),
                ('emp_status', models.SmallIntegerField(blank=True, null=True)),
                ('emp_payid', models.SmallIntegerField(blank=True, null=True)),
                ('salary_active', models.BooleanField(blank=True, null=True)),
                ('emp_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('emp_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emp_template', models.SmallIntegerField(blank=True, null=True)),
                ('emp_join_date', models.DateTimeField(blank=True, null=True)),
                ('emp_term_date', models.DateTimeField(blank=True, null=True)),
                ('emp_work', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('emp_lve_id', models.CharField(blank=True, max_length=5, null=True)),
                ('emp_acc_no', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_acc_type', models.SmallIntegerField(blank=True, null=True)),
                ('emp_acc_bank', models.SmallIntegerField(blank=True, null=True)),
                ('emp_acc_brn', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_acc_city', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('emp_tax', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_last_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emp_last_wht', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emp_house', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emp_insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emp_donation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emp_family', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emp_doc_no', models.CharField(blank=True, max_length=10, null=True)),
                ('sch_active', models.BooleanField(blank=True, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('empstatus', models.CharField(blank=True, db_column='EmpStatus', max_length=1, null=True)),
                ('emp_wkcountry', models.SmallIntegerField(blank=True, null=True)),
                ('emp_spid', models.CharField(blank=True, db_column='emp_SpID', max_length=10, null=True)),
                ('emp_jobfnt', models.CharField(blank=True, max_length=6, null=True)),
                ('emp_cate', models.SmallIntegerField(blank=True, null=True)),
                ('emp_headcount', models.CharField(blank=True, max_length=5, null=True)),
                ('randomno', models.DecimalField(blank=True, db_column='RandomNo', decimal_places=0, max_digits=18, null=True)),
                ('emp_loan', models.DecimalField(blank=True, db_column='Emp_Loan', decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'EMPLOYEE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(blank=True, max_length=2, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
