# Generated by Django 3.0.7 on 2020-06-29 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='language',
            new_name='language_code',
        ),
    ]
