# Generated by Django 3.0.7 on 2020-06-29 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200629_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='employee_id',
        ),
    ]
