# Generated by Django 3.1.2 on 2020-11-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpPhoto',
            fields=[
                ('emp_id', models.DecimalField(decimal_places=0, max_digits=7, primary_key=True, serialize=False)),
                ('image_title', models.CharField(blank=True, max_length=100, null=True)),
                ('image_path', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.BinaryField(blank=True, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'EMP_PHOTO',
                'managed': False,
            },
        ),
    ]
