# Generated by Django 3.1.2 on 2020-10-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchPlan',
            fields=[
                ('sch_no', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('srv_id', models.DecimalField(blank=True, decimal_places=0, max_digits=16, null=True)),
                ('cnt_id', models.DecimalField(blank=True, decimal_places=0, max_digits=13, null=True)),
                ('emp_id', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('sch_rank', models.CharField(blank=True, max_length=3, null=True)),
                ('relief', models.BooleanField(blank=True, null=True)),
                ('sch_date_frm', models.DateTimeField(blank=True, null=True)),
                ('sch_date_to', models.DateTimeField(blank=True, null=True)),
                ('sch_shf_mon', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('sch_shf_tue', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('sch_shf_wed', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('sch_shf_thu', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('sch_shf_fri', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('sch_shf_sat', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('sch_shf_sun', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('sch_active', models.BooleanField(blank=True, null=True)),
                ('upd_date', models.DateTimeField(blank=True, null=True)),
                ('upd_by', models.CharField(blank=True, max_length=10, null=True)),
                ('upd_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'SCH_PLAN',
                'managed': False,
            },
        ),
    ]
