# Generated by Django 3.1.2 on 2020-10-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_schplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schplan',
            options={'managed': True},
        ),
    ]
