# Generated by Django 3.1.2 on 2020-10-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('monitoring', '0003_auto_20201027_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schplan',
            name='emp_id',
            field=models.ForeignKey(db_column='emp_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sch_plan_employee_fk', to='employee.employee'),
        ),
    ]
