# Generated by Django 3.0.7 on 2021-03-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_access_export_customer_address_main_report', 'Can accces Export Customer Address (Main) report'),),
            },
        ),
    ]
