# Generated by Django 3.0.7 on 2021-06-14 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19report', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Covid19Reports',
            new_name='Covid19Report',
        ),
        migrations.AlterModelOptions(
            name='covid19report',
            options={'permissions': (('can_access_covid_19_report', 'Can access Covid 19 report'),)},
        ),
    ]
